rosetta.config:
    store:     true
    translate: true
    
rosetta.scanners:
    php:  Bundle\RosettaBundle\Scanner\PhpScanner
    twig: Bundle\RosettaBundle\Scanner\TwigScanner
    
rosetta.live:
    store:     true
    translate: true
    choose:    true