rosetta.config:
    locale:        ~     # current locale
    scanners:
        *.php:     Bundle\RosettaBundle\Service\Scanner\PhpScanner
        *.twig:    Bundle\RosettaBundle\Service\Scanner\TwigScanner
    translator: 
        adapter:   Bundle\RosettaBundle\Translator\GoogleAdapter
        key:       MY_GOOLGLE_TRANSLATE_KEY
        version:   2
    live:
        enabled:   true  # store scanned messages
        translate: true  # translate scanned messages
        choose:    true  # choose best/translated message
