rosetta.config:
    translator:
        locale:       %session.default_locale%
        adapter:      Bundle\RosettaBundle\Service\Translator\GoogleAdapter
        config:
            key:      YOUR_GOOGLE_TRANSLATE_KEY
            version:  2
    locator:          ~
    deployer:         ~
    workflow:         ~
    scanner:
        translate:    true
        choose:       true
        deploy:       true
        adapters:
            *.php:    Bundle\RosettaBundle\Service\Scanner\PhpScanner
            *.twig:   Bundle\RosettaBundle\Service\Scanner\TwigScanner
    importer:
        translate:    true
        choose:       true
        deploy:       true
    live:
        enabled:      true
        update:       false
        translate:    true
        choose:       true
        deploy:       false
